# ALZ Management Group deployment pipeline
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 1-management-groups/**
      - pipelines/mgmt-groups.yml

pool:
  name: Default   # <-- self-hosted agent pool

variables:
  TF_VERSION: '1.6.6'

steps:
- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: $(TF_VERSION)

- task: AzureCLI@2
  displayName: "Terraform deploy (1-management-groups)"
  inputs:
    azureSubscription: 'ALZ_SC_01'
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      $ErrorActionPreference = "Stop"
      Set-Location "1-management-groups"

      # Clean any cached backend config from previous runs on the agent
      if (Test-Path ".terraform") { Remove-Item ".terraform" -Recurse -Force }
      if (Test-Path ".terraform.lock.hcl") { Remove-Item ".terraform.lock.hcl" -Force }

      terraform init -input=false -reconfigure

      terraform fmt -check
      terraform validate
      terraform apply -auto-approve -input=false
      terraform output -json
