trigger: none

pool:
  name: Default
  demands:
    - Agent.OS -equals Windows_NT

workspace:
  clean: all

variables:
  TF_VERSION: '1.6.6'
  TF_WORKING_DIR: '1-management-groups'
  TFVARS_FILE: '../environments/dev.tfvars'
  BACKEND_KEY: 'alz/1-management-groups.tfstate'

steps:
- checkout: self
  clean: true

- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: $(TF_VERSION)

# --- DEBUG: prove which commit + file is being executed ---
- powershell: |
    Write-Host "Build.SourceVersion: $(Build.SourceVersion)"
    Write-Host "Build.SourceBranch: $(Build.SourceBranch)"
    Write-Host "Repo root:"
    Get-ChildItem -Force
    Write-Host "---- main.tf (line numbered) ----"
    $i=1
    Get-Content "$(TF_WORKING_DIR)\main.tf" | ForEach-Object { "{0,4}: {1}" -f $i, $_; $i++ }
  displayName: 'DEBUG: show commit + main.tf'
  
# -----------------------
# Terraform INIT
# -----------------------
- task: TerraformTaskV5@5
  displayName: 'Terraform Init (1-management-groups)'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(TF_WORKING_DIR)'
    backendServiceArm: 'ALZ_SC_01'
    backendAzureRmResourceGroupName: 'terraform-storage-rg'
    backendAzureRmStorageAccountName: 'terraformstate277'
    backendAzureRmContainerName: 'tfstatefiles'
    backendAzureRmKey: '$(BACKEND_KEY)'
    allowTelemetryCollection: false

# -----------------------
# Terraform VALIDATE
# -----------------------
- task: TerraformTaskV5@5
  displayName: 'Terraform Validate (1-management-groups)'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(TF_WORKING_DIR)'
    allowTelemetryCollection: false

# -----------------------
# GUARD (must pass)
# -----------------------
- powershell: |
    Write-Host "Commit: $(Build.SourceVersion)"
    $line = (Get-Content "1-management-groups\main.tf" | Select-String "parent_management_group_id").Line
    Write-Host "Detected parent line: $line"
    if ($line -match "var\.tenant_root_mg_id") { throw "STOP: still using old main.tf" }
  displayName: "GUARD: confirm updated main.tf is used"

# -----------------------
# Terraform PLAN
# -----------------------
- task: TerraformTaskV5@5
  displayName: 'Terraform Plan (1-management-groups)'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(TF_WORKING_DIR)'
    environmentServiceNameAzureRM: 'ALZ_SC_01'
    commandOptions: >
      -var-file=$(TFVARS_FILE)
      -var="tenant_root_mg_id=/providers/Microsoft.Management/managementGroups/33511258-7b0d-4c95-88ae-d819e1fcf22d"
      -out=tfplan
    allowTelemetryCollection: false

# -----------------------
# Terraform APPLY
# -----------------------
- task: TerraformTaskV5@5
  displayName: 'Terraform Apply (1-management-groups)'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(TF_WORKING_DIR)'
    environmentServiceNameAzureRM: 'ALZ_SC_01'
    commandOptions: >
      -var="tenant_root_mg_id=/providers/Microsoft.Management/managementGroups/33511258-7b0d-4c95-88ae-d819e1fcf22d"
      tfplan
    allowTelemetryCollection: false
