trigger: none

pool:
  name: Default
  demands:
    - Agent.OS -equals Windows_NT

workspace:
  clean: all

variables:
  TF_VERSION: '1.6.6'
  TF_WORKING_DIR: '1-management-groups'
  TFVARS_FILE: '../environments/dev.tfvars'
  BACKEND_KEY: 'alz/1-management-groups.tfstate'

steps:
- checkout: self
  clean: true

- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: $(TF_VERSION)

# Debug (optional but recommended)
- powershell: |
    Write-Host "Commit: $(Build.SourceVersion)"
    Write-Host "Branch: $(Build.SourceBranch)"
    Write-Host "Repo: $(Build.Repository.Name)"
    Write-Host "Parent MG line(s) in main.tf:"
    Select-String -Path "$(TF_WORKING_DIR)\main.tf" -Pattern "parent_management_group_id|tenant_root_mg_name"
    Write-Host "dev.tfvars:"
    Get-Content "environments\dev.tfvars"
  displayName: "DEBUG: confirm files used"

# INIT
- task: TerraformTask@5
  displayName: 'Terraform Init (1-management-groups)'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(TF_WORKING_DIR)'
    backendServiceArm: 'ALZ_SC_01'
    backendAzureRmResourceGroupName: 'terraform-storage-rg'
    backendAzureRmStorageAccountName: 'terraformstate277'
    backendAzureRmContainerName: 'tfstatefiles'
    backendAzureRmKey: '$(BACKEND_KEY)'
    backendAzureRmUseEntraIdForAuthentication: true
    allowTelemetryCollection: false

# VALIDATE
- task: TerraformTask@5
  displayName: 'Terraform Validate (1-management-groups)'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(TF_WORKING_DIR)'
    allowTelemetryCollection: false

# PLAN
- task: TerraformTask@5
  displayName: 'Terraform Plan (1-management-groups)'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(TF_WORKING_DIR)'
    environmentServiceNameAzureRM: 'ALZ_SC_01'
    commandOptions: '-var-file=$(TFVARS_FILE) -out=tfplan'
    allowTelemetryCollection: false

# APPLY
- task: TerraformTask@5
  displayName: 'Terraform Apply (1-management-groups)'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(TF_WORKING_DIR)'
    environmentServiceNameAzureRM: 'ALZ_SC_01'
    commandOptions: 'tfplan'
    allowTelemetryCollection: false
