# ALZ Management Group deployment pipeline
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 1-management-groups/**
      - pipelines/mgmt-groups.yml

pool:
  name: Default   # <-- self-hosted agent pool

variables:
  TF_VERSION: '1.6.6'

steps:
- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: $(TF_VERSION)

- task: AzureCLI@2
  displayName: "Terraform deploy (1-management-groups)"
  inputs:
    azureSubscription: 'ALZ_SC_01'
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      $ErrorActionPreference = "Stop"
      Set-Location "1-management-groups"

      terraform init -input=false
      terraform fmt -check
      terraform validate
      terraform plan -out tfplan -input=false
      terraform apply -auto-approve -input=false tfplan
      terraform output -json