trigger: none

pool:
  name: Default
  demands:
    - Agent.OS -equals Windows_NT

variables:
  TF_VERSION: '1.6.6'

steps:
- checkout: self
  clean: true

- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: $(TF_VERSION)

# INIT (separate state file for MGs)
- task: TerraformTask@5
  displayName: Terraform Init (1-management-groups)
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '1-management-groups'
    backendServiceArm: 'ALZ_SC_01'
    backendAzureRmResourceGroupName: 'terraform-storage-rg'
    backendAzureRmStorageAccountName: 'terraformstate277'
    backendAzureRmContainerName: 'tfstatefiles'
    backendAzureRmKey: 'alz/1-management-groups.tfstate'
    backendAzureRmUseEntraIdForAuthentication: true

- task: TerraformTask@5
  displayName: Terraform Validate (1-management-groups)
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '1-management-groups'

- task: TerraformTask@5
  displayName: Terraform Plan (1-management-groups)
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '1-management-groups'
    environmentServiceNameAzureRM: 'ALZ_SC_01'
    commandOptions: '-var-file=../environments/dev.tfvars -out=tfplan'

- task: TerraformTask@5
  displayName: Terraform Apply (1-management-groups)
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '1-management-groups'
    environmentServiceNameAzureRM: 'ALZ_SC_01'
    commandOptions: 'tfplan'
