# ALZ Management Group deployment pipeline
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 1-management-groups/**
      - pipelines/mgmt-groups.yml

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: '1.6.6'

steps:
- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: $(TF_VERSION)

- task: AzureCLI@2
  displayName: "Terraform deploy (1-management-groups)"
  inputs:
    azureSubscription: 'ALZ_SC01'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -e
      cd 1-management-groups
      terraform init -input=false
      terraform fmt -check
      terraform validate
      terraform plan -out tfplan -input=false
      terraform apply -auto-approve -input=false tfplan
      terraform output -json